spring:
  profiles:
    active: prod
  application:
    name: SpringDemoTest
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 2000ms
    requested-heartbeat: 30
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: ""
#      timeout: 60s
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 30s
springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-exclude: com.scalar

scalar:
#  theme: deepSpace
#  layout: modern
#  documentDownloadType: both
  url: /v3/api-docs
  path: /docs
  enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#server:
#  port: 8088
#        include: scalar, health, info

